Specify list/map capacity when initializing where possible
microsoft/onnxruntime pull request #11110
Opened 2022-04-04 21:14 UTC by mina-asham

- This really depends on the use case, but in some cases the array/map resizing can be slightly costly, there is effectively no downside setting the initial capacity for a collection if we know for sure its final size

**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

2022-04-12 20:21 UTC, faxu commented
@Craigacp can you help review this?

2022-04-12 20:56 UTC, Craigacp requested changes
I don't think it's worth adding a whole class for the single method, so move that to `OrtUtil`, and then otherwise that's fine.

I'm kinda surprised that this was an issue given the size of the objects that are usually returned by those methods (where the default capacity is probably bigger than the sized one anyway), and the relative amount of computation in Java vs the ORT native code, but it doesn't really make much difference to include it.

2022-04-12 20:56 UTC, Craigacp commented on java/src/main/java/ai/onnxruntime/MapUtil.java
> +  static int capacityFromSize(int size) {
Can you move this method onto the existing `OrtUtil` utility class?

2022-04-13 10:02 UTC, mina-asham commented
> I don't think it's worth adding a whole class for the single method, so move that to `OrtUtil`, and then otherwise that's fine.
> 
> I'm kinda surprised that this was an issue given the size of the objects that are usually returned by those methods (where the default capacity is probably bigger than the sized one anyway), and the relative amount of computation in Java vs the ORT native code, but it doesn't really make much difference to include it.

I can confirm that most of the time in our OrtSession is not coming from native code, from JFR I also see a good chunk is coming from there, I don't expect the change to be noticeable for *most* cases but I expect an enhancement for ours and the rest should be same or better after this.

2022-04-13 16:26 UTC, mina-asham commented on java/src/test/java/ai/onnxruntime/OrtUtilTest.java
> +  void capacityFromSize() {
Done

2022-04-13 17:00 UTC, faxu commented
/azp run onnxruntime-python-checks-ci-pipeline, orttraining-amd-gpu-ci-pipeline, orttraining-linux-ci-pipeline, orttraining-linux-gpu-ci-pipeline, orttraining-ortmodule-distributed, 
ONNX Runtime Web CI Pipeline, onnxruntime-binary-size-checks-ci-pipeline

2022-04-27 18:16 UTC, mina-asham commented
@faxu any blockers for merging this one?

2022-04-28 02:08 UTC, faxu commented
@pranavsharma any concerns on this PR?

2022-04-28 03:58 UTC, pranavsharma approved these changes

2022-04-28 03:59 UTC, merged