Cjian/1.14.0 fix
microsoft/onnxruntime pull request #14682
Opened 2023-02-15 00:08 UTC by jchen351

### Description

### Motivation and Context

2023-02-15 02:24 UTC, mszhanyi approved these changes

2023-02-15 16:06 UTC, mszhanyi requested changes
could you take a look https://dev.azure.com/aiinfra/Lotus/_build/results?buildId=276719&view=artifacts&pathAsName=false&type=publishedArtifacts
Why onnxruntime-1.14.0-cp39-cp39-macosx_11_0_x86_64.whl  is ***_11_0**, not 10_15?
The ***_11_0_x86_64.whl could NOT be installed, but ***_10_15_x86_64.whl could.

In my Mac Pro, the x86_64 package for python38 works, but the package for python39 doesn't.

For 1.13, it's xxx_10_15.whl
https://files.pythonhosted.org/packages/2b/16/919c5a918ce4cbc349638ed2a10b482b1282fcdea11f4f1892c41caf481f/onnxruntime-1.13.1-cp39-cp39-macosx_10_15_x86_64.whl

2023-02-16 02:55 UTC, mszhanyi approved these changes

2023-02-16 03:21 UTC, wejoncy approved these changes

2023-02-16 03:22 UTC, merged