Add tensor to Data URL utill function
microsoft/onnxruntime pull request #14681
Opened 2023-02-14 23:20 UTC by shalvamist

### Description
Added a function to convert tensor to Data URL
Updated the E2E test to cover more configurations of tensor <--> Image utill functions

Updated tensor <--> image utill function implementation -
* Changed offset to stride (better name)
* Changed the naming on string use case since it covers both Data URL & URLs on the web

2023-02-15 00:42 UTC, fs-eire commented on js/web/test/e2e/browser-test-wasm-image-tensor-image.js
> +  }
The CodeQL warning means that you missed a semicolon here. It took me a while to understand what it meant.

2023-02-16 00:57 UTC, guschmue requested changes

2023-02-16 16:43 UTC, shalvamist commented on js/common/lib/tensor.ts
> +   * @param string - {string} - Assuming the string is a URL to an image or Data URL
I kinda agree that string:string is strange. My issue was distinguishing between URL & dataURL. 
One is pure data and the other is just a string directing to the data both are strings so I used string but maybe 'urlSource' will be a better name ?

2023-02-16 16:47 UTC, shalvamist commented on js/common/lib/tensor-impl.ts
> +    const image = this.toImageData(options);
Yeah, it's easy to do but the function name is detailing the return value, so we'll have to change the naming convention or reuse the code from toImageData in DataURL.

2023-02-17 17:07 UTC, guschmue commented on js/common/lib/tensor.ts
> +   * @param string - {string} - Assuming the string is a URL to an image or Data URL
urlSource, dataSource, imageSource or maybe just source might be good.

2025-07-03 18:08 UTC, closed without merging