Ortmodule onnx input support
microsoft/onnxruntime pull request #7691
Opened 2021-05-14 00:08 UTC by almaly-microsoft

ORTmodule wraps pytorch model and executes training for it. However pytorch models are stored in ONNX format and in some cases (like quantization emulation) they needs to be retrained to get accuracy back.

This change is about adding that support. I updated one test to store pytorch model into ONNX format and then passed it into ORTModule. Training runs well.

2021-05-14 00:11 UTC, almaly-microsoft commented on orttraining/orttraining/python/training/ortmodule/_graph_execution_manager.py
> +        self._use_external_gpu_allocator = False
Rollback

2021-05-14 00:12 UTC, almaly-microsoft commented on orttraining/orttraining/python/training/ortmodule/_graph_execution_manager.py
> +        self._run_symbolic_shape_infer = False
Rollback

2021-05-14 00:15 UTC, almaly-microsoft commented on orttraining/orttraining/python/training/ortmodule/_io.py
> +        kwargs = {kwarg_name: arg for kwarg_name, arg in zip(self.keyword_names, flat_args[self.num_positionals:])}
check why that happened. didn't change that

2021-06-14 23:37 UTC, mrry requested changes
Sorry for the delay on this review, and thanks for bearing with us while we were doing the release, Aleksandr.

2021-06-18 23:16 UTC, almaly-microsoft commented on orttraining/orttraining/python/training/ortmodule/_training_manager.py
> +                                                    [p[1] for p in self._onnx_model_parameters],
merged in, thanks

2021-06-21 19:30 UTC, almaly-microsoft commented on orttraining/orttraining/python/training/ortmodule/ortmodule.py
> -            self.forward.__func__, module.forward.__func__)
it is intentional as onnx graph doesn't have forward method

2021-06-22 00:29 UTC, almaly-microsoft commented on orttraining/orttraining/python/training/ortmodule/_graph_execution_manager.py
> +            initializer_names_to_train = [initializer.name for initializer in self._onnx_model.graph.initializer]
I haven't tried anything that is more advanced that model in orttraining_test_ortmodule_poc.py

2021-06-22 15:36 UTC, thiagocrepaldi commented
I will start analyzing this PR soon and propose changes to both ORTModule and this PR so that this PR can be plugged in a modular way

2022-01-03 19:10 UTC, thiagocrepaldi commented
closed due to inactivity

2022-01-03 19:10 UTC, closed without merging